/* for user sign in*/
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

/* for new user registration */
export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";

/* for retrieving all articles */
export const ARTICLES_REQUEST = "ARTICLES_REQUEST";
export const ARTICLES_SUCCESS = "ARTICLES_SUCCESS";
export const ARTICLES_FAIL = "ARTICLES_FAIL";
