/* for user sign in*/
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

/* for new user registration */
export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";

/* for retrieving all articles */
export const ARTICLES_REQUEST = "ARTICLES_REQUEST";
export const ARTICLES_SUCCESS = "ARTICLES_SUCCESS";
export const ARTICLES_FAIL = "ARTICLES_FAIL";

/* for follow action */
export const USER_FOLLOWING_REQUEST = "USER_FOLLOWING_REQUEST";
export const USER_FOLLOWING_SUCCESS = "USER_FOLLOWING_SUCCESS";
export const USER_FOLLOWING_FAIL = " USER_FOLLOWING_FAIL";

/* for unfollow action */
export const USER_UNFOLLOWING_REQUEST = "USER_UNFOLLOWING_REQUEST";
export const USER_UNFOLLOWING_SUCCESS = "USER_UNFOLLOWING_SUCCESS";
export const USER_UNFOLLOWING_FAIL = " USER_UNFOLLOWING_FAIL";

/* for favorite action */
export const USER_FAVORITE_REQUEST = "USER_FAVORITE_REQUEST";
export const USER_FAVORITE_SUCCESS = "USER_FAVORITE_SUCCESS";
export const USER_FAVORITE_FAIL = " USER_FAVORITE_FAIL";

/* for unfavorite action */
export const USER_UNFAVORITE_REQUEST = "USER_UNFAVORITE_REQUEST";
export const USER_UNFAVORITE_SUCCESS = "USER_UNFAVORITE_SUCCESS";
export const USER_UNFAVORITE_FAIL = " USER_UNFAVORITE_FAIL";

/* for like article action */
export const ARTICLES_LIKE_REQUEST = "ARTICLES_LIKE_REQUEST";
export const ARTICLES_LIKE_SUCCESS = "ARTICLES_LIKE_SUCCESS";
export const ARTICLES_LIKE_FAIL = " ARTICLES_LIKE_FAIL";

/* for dislike article action */
export const ARTICLES_DISLIKE_REQUEST = "ARTICLES_DISLIKE_REQUEST";
export const ARTICLES_DISLIKE_SUCCESS = "ARTICLES_DISLIKE_SUCCESS";
export const ARTICLES_DISLIKE_FAIL = " ARTICLES_DISLIKE_FAIL";
